import turtle
t = turtle.Turtle()
t.shape('turtle')
t.right(35)
t.forward(40)
t.right(80)
t.forward(40)
t.right(60)
t.forward(40)
t.right(50)
t.forward(40)
t.right(70)
t.forward(40)
t.right(65)
t.forward(35)
t.penup()
t.right (90)
t.forward(30)
t.pendown
turtle.done()